name: format-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: actions/checkout@v5
      - name: Install JuliaFormatter and SciMLStyle
        run: |
          using Pkg
          Pkg.add(; name="JuliaFormatter")
          Pkg.add(; name="SciMLStyle")
        shell: julia --color=yes {0}
      - name: Run formatter
        run: |
          using JuliaFormatter
          using SciMLStyle
          format("."; style=SciMLStyle(), verbose=true)
        shell: julia --color=yes {0}
      - name: Format check
        run: |
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end
        shell: julia --color=yes {0}